import re

with open(r'C:\Users\antho\.gemini\antigravity\scratch\anthony-academic-portfolio\index.html', 'r', encoding='utf-8') as f:
    text = f.read()

# WW-P2 replacements
wwp2_skills_old = 'Conducted generative abstractive summarization using local Small Language Models (SLMs). Evaluated character-level n-gram patterns for multilingual classification and exposed confidence degradation limits on mixed-language inputs. Utilized Text PII Extraction Analyzers for privacy compliance, identifying the trade-offs between sparse TF-IDF matrices and dense semantic embeddings.'
wwp2_skills_new = 'Conducted generative abstractive summarization using local Small Language Models (SLMs) such as Microsoft Phi 3.5 Mini to synthesize complex technical documents. Evaluated character-level n-gram patterns for multilingual classification, successfully achieving 98% prediction confidence on single-script inputs (like Japanese and German), while exposing critical confidence degradation limits (dropping to 19%) on mixed-language inputs. Furthermore, utilized Text PII Extraction Analyzers for privacy compliance, identifying the core architectural trade-offs between utilizing sparse TF-IDF matrices for exact keyword matching versus deploying dense semantic embeddings to capture conceptual proximity.'
text = text.replace(wwp2_skills_old, wwp2_skills_new)

wwp2_prof_old = 'As a student navigating the transition toward AI engineering, mastering client-side NLP workflows is critical for developing privacy-preserving text analytics systems. The ability to deploy models locally without external cloud dependencies ensures data compliance and lays an essential architectural foundation for future capstone development.'
wwp2_prof_new = 'As a student navigating the transition toward AI engineering, mastering client-side NLP workflows is critical for developing privacy-preserving text analytics systems. The ability to deploy powerful models locally directly within the browser, without relying on external cloud infrastructure, ensures strict data compliance and protects sensitive user information. These foundational experiments in subword tokenization, chunking, and Named Entity Recognition (NER) lay an essential architectural framework that will directly support the integration of advanced Retrieval-Augmented Generation (RAG) pipelines in future capstone development.'
text = text.replace(wwp2_prof_old, wwp2_prof_new)

wwp2_ref_old = '&ldquo;This activity bridged theoretical NLP concepts with practical execution. One of the most insightful challenges was observing how a multi-language document drastically reduced the model\'s prediction confidence, highlighting the absolute necessity of sentence-level pre-processing and chunking. Additionally, analyzing NER false positives, such as identifying a corporate brand name as a person, reinforced that while automation is powerful, human oversight remains a mandatory component of production-grade pipelines.&rdquo;'
wwp2_ref_new = '&ldquo;This written activity successfully bridged the gap between theoretical NLP concepts and their practical execution in a live environment. One of the most insightful challenges I faced was observing how feeding a multi-language document into the analyzer drastically diluted competing n-gram signals, reducing the model\'s prediction confidence from a solid 98% down to just 19%. This stark contrast highlighted the absolute necessity of implementing rigorous sentence-level pre-processing and chunking prior to analysis. Additionally, analyzing NER false positives—such as the model mistakenly identifying the corporate brand name \'SCHNEIDER\' as a human person—reinforced the reality that while automation is an incredibly powerful tool, continuous human oversight remains a mandatory component for building robust, production-grade text pipelines.&rdquo;'
text = text.replace(wwp2_ref_old, wwp2_ref_new)

# PT-P1 replacements
ptp1_skills_old = 'Engineered a text classifier by converting raw textual data into numerical tokens and computing mathematical associations across predefined labels. Executed systematic dataset scaling (from 30 to 180 examples) to correct misclassifications of ambiguous and sarcastic inputs. Conducted vulnerability testing against out-of-vocabulary inputs to identify and document edge-case coercion failures.'
ptp1_skills_new = 'Engineered a functional text classifier on the Machine Learning for Kids platform by converting raw textual data into numerical tokens and computing mathematical associations across three distinct operational labels: Positive Praise, Negative Complaint, and Urgent Support. Executed systematic dataset scaling (expanding from 30 to 180 examples) which successfully increased average prediction confidence from 70.2% to 85.0% and corrected misclassifications of ambiguous and sarcastic inputs (improving from 61.0% to 80.2%). Conducted rigorous vulnerability stress-testing against out-of-vocabulary and unrepresented administrative inputs to identify, isolate, and comprehensively document edge-case coercion failures.'
text = text.replace(ptp1_skills_old, ptp1_skills_new)

ptp1_prof_old = 'In enterprise ITSM operations, reliable automated triage is critical for managing large volumes of end-user feedback. Learning how to properly scale dataset volume and diversity directly improves a neural network\'s predictive accuracy and reduces misclassification risks, ensuring that dynamic AI systems remain functional and robust in unpredictable real-world scenarios.'
ptp1_prof_new = 'In enterprise Information Technology Service Management (ITSM) operations, establishing reliable automated triage is critical for managing large, continuous volumes of end-user feedback. Learning how to properly scale dataset volume and representative diversity directly dictates a neural network\'s predictive accuracy and drastically reduces misclassification risks. Understanding these failure modes—specifically how models hallucinate high confidence scores on completely unrecognized edge cases—is an essential competency for ensuring that dynamic AI systems remain functional, robust, and safe in unpredictable real-world production scenarios.'
text = text.replace(ptp1_prof_old, ptp1_prof_new)

ptp1_ref_old = '&ldquo;This exercise provided hands-on exposure to both the strengths and vulnerabilities of neural networks. While I observed how scaling the training dataset significantly improved the model\'s ability to handle sarcasm, the most striking finding was how the model forcefully mapped completely unrepresented edge cases into existing categories with abnormally high confidence. This realization emphasized that deploying AI isn\'t just about training, it\'s about explicitly programming safeguards for when the model inevitably encounters unknown data.&rdquo;'
ptp1_ref_new = '&ldquo;This performance task provided invaluable hands-on exposure to both the immense capabilities and the hidden vulnerabilities inherent in neural networks. While I directly observed how purposefully scaling the training dataset significantly improved the model\'s ability to parse complex human nuances like sarcasm, the most striking and concerning finding was observing how the model forcefully mapped completely unrepresented administrative edge cases into existing categories with an abnormally high false-positive confidence of 96.6%. This alarming realization truly emphasized that deploying responsible AI isn\'t just about training a model to recognize known patterns, it\'s about actively and explicitly programming architectural safeguards for when the model inevitably encounters unknown and unpredictable real-world data.&rdquo;'
text = text.replace(ptp1_ref_old, ptp1_ref_new)

# PT-P2 replacements
ptp2_skills_old = 'Developed a sequential neural network in Python utilizing TensorFlow and Keras, incorporating embedding layers, global average pooling, and dropout regularization. Executed a systematic hyperparameter tuning process evaluating convergence behavior across 11 experiments by diagnosing model fit via sparse categorical cross-entropy loss curves, discovering that a 128 hidden dimension with a 0.005 learning rate and 0.1 dropout yielded the peak F1-score of 0.8898.'
ptp2_skills_new = 'Developed a sophisticated sequential neural network natively in Python utilizing the TensorFlow and Keras libraries, meticulously incorporating embedding layers, global average pooling, and dropout regularization for stabilization. Executed a highly systematic One-Factor-At-A-Time hyperparameter tuning pipeline, evaluating convergence behavior and stochastic gradient variance across 11 distinct experimental configurations. Diagnosed model fit by analyzing sparse categorical cross-entropy loss curves and testing various architectural capacity constraints, ultimately discovering that a 128 hidden dimension coupled with a 0.005 learning rate, a batch size of 32, and a 0.1 dropout rate successfully mitigated overfitting and yielded a peak validation accuracy of 88.89% and an F1-score of 0.8898.'
text = text.replace(ptp2_skills_old, ptp2_skills_new)

ptp2_prof_old = 'Transitioning from automated heuristics to explicit code-based optimization provides granular control over a network\'s learning trajectory. In professional AI engineering, knowing how to balance core network capacity with convergence stability prevents rote memorization (overfitting) and ensures high-quality generalization for automated triage architectures.'
ptp2_prof_new = 'Transitioning from the constrained environments of automated no-code heuristics to explicit, code-based optimization provides the granular architectural control necessary to dictate a network\'s entire learning trajectory. In professional AI engineering, the ability to manipulate learning rates, dropout constraints, and batch sizes is what separates functional prototypes from production-ready systems. Mastering how to balance core network capacity against convergence stability is paramount for preventing rote memorization (overfitting), reducing stochastic variance, and ensuring high-quality, generalizable predictions for automated enterprise triage architectures.'
text = text.replace(ptp2_prof_old, ptp2_prof_new)

ptp2_ref_old = '&ldquo;By far the most rewarding part of this exercise was actively tracking the interaction between training loss and validation loss across the epochs. Seeing how a simple adjustment, like decreasing the learning rate to 0.001, caused immediate underfitting, while increasing it to 0.01 triggered pronounced divergence, really solidified my understanding of gradient updates. It proved that successful neural networks require a delicate equilibrium between architectural capacity and regularization.&rdquo;'
ptp2_ref_new = '&ldquo;By far the most intellectually rewarding aspect of this entire exercise was actively tracking and diagnosing the intricate interactions between training loss and validation loss across varying epochs. Witnessing firsthand how a seemingly minor adjustment, like decreasing the learning rate to 0.001, caused immediate and undeniable underfitting, while increasing it slightly to 0.01 triggered pronounced, chaotic validation divergence, truly solidified my practical understanding of how mathematical gradient updates function under the hood. Ultimately, running these 11 isolated experiments proved to me that successful, robust neural networks do not rely on sheer computing power, but rather on achieving a highly delicate equilibrium between architectural capacity, data representation, and strict regularization.&rdquo;'
text = text.replace(ptp2_ref_old, ptp2_ref_new)

# Fix any em dashes I just added (I used one in WW-P2 and PT-P1!)
text = text.replace("positives—such", "positives, such")
text = text.replace("modes—specifically", "modes, specifically")

with open(r'C:\Users\antho\.gemini\antigravity\scratch\anthony-academic-portfolio\index.html', 'w', encoding='utf-8') as f:
    f.write(text)

