import re

with open(r'C:\Users\antho\.gemini\antigravity\scratch\anthony-academic-portfolio\index.html', 'r', encoding='utf-8') as f:
    text = f.read()

# WW-P2 Replacements
old_wwp2_skills = 'Conducted generative abstractive summarization using local Small Language Models (SLMs) such as Microsoft Phi 3.5 Mini to synthesize complex technical documents. Evaluated character-level n-gram patterns for multilingual classification, successfully achieving 98% prediction confidence on single-script inputs (like Japanese and German), while exposing critical confidence degradation limits (dropping to 19%) on mixed-language inputs. Furthermore, utilized Text PII Extraction Analyzers for privacy compliance, identifying the core architectural trade-offs between utilizing sparse TF-IDF matrices for exact keyword matching versus deploying dense semantic embeddings to capture conceptual proximity.'
new_wwp2_skills = 'Ran generative summarization using local Small Language Models (SLMs) like Microsoft Phi 3.5 Mini to process technical documents. Tested character-level n-gram patterns for language classification, hitting 98% confidence on single languages but dropping to 19% on mixed-language text. Also used Text PII Extraction Analyzers for privacy compliance, comparing the pros and cons of using TF-IDF matrices for exact keyword matching versus using dense semantic embeddings.'
text = text.replace(old_wwp2_skills, new_wwp2_skills)

old_wwp2_prof = 'As a student navigating the transition toward AI engineering, mastering client-side NLP workflows is critical for developing privacy-preserving text analytics systems. The ability to deploy powerful models locally directly within the browser, without relying on external cloud infrastructure, ensures strict data compliance and protects sensitive user information. These foundational experiments in subword tokenization, chunking, and Named Entity Recognition (NER) lay an essential architectural framework that will directly support the integration of advanced Retrieval-Augmented Generation (RAG) pipelines in future capstone development.'
new_wwp2_prof = 'Learning how to run NLP workflows locally on a client machine is a great skill for building secure analytics systems. Being able to run models directly in the browser without relying on cloud servers helps keep sensitive data safe and compliant. Understanding subword tokenization, chunking, and Named Entity Recognition (NER) also builds a solid foundation for integrating more advanced Retrieval-Augmented Generation (RAG) pipelines in future professional projects.'
text = text.replace(old_wwp2_prof, new_wwp2_prof)

old_wwp2_ref = '&ldquo;This written activity successfully bridged the gap between theoretical NLP concepts and their practical execution in a live environment. One of the most insightful challenges I faced was observing how feeding a multi-language document into the analyzer drastically diluted competing n-gram signals, reducing the model\'s prediction confidence from a solid 98% down to just 19%. This stark contrast highlighted the absolute necessity of implementing rigorous sentence-level pre-processing and chunking prior to analysis. Additionally, analyzing NER false positives, such as the model mistakenly identifying the corporate brand name \'SCHNEIDER\' as a human person, reinforced the reality that while automation is an incredibly powerful tool, continuous human oversight remains a mandatory component for building robust, production-grade text pipelines.&rdquo;'
new_wwp2_ref = '&ldquo;This activity was a great way to connect NLP theory with actual implementation. One of the most interesting challenges was seeing how feeding a mixed-language document into the analyzer confused the model, dropping its confidence from 98% down to just 19%. This really showed me why we need to properly separate and pre-process text beforehand. On top of that, seeing the model incorrectly flag the company name \'SCHNEIDER\' as a person proved that no matter how good the automation gets, having a human in the loop is still necessary for real-world applications.&rdquo;'
text = text.replace(old_wwp2_ref, new_wwp2_ref)


# PT-P1 Replacements
old_ptp1_skills = 'Engineered a functional text classifier on the Machine Learning for Kids platform by converting raw textual data into numerical tokens and computing mathematical associations across three distinct operational labels: Positive Praise, Negative Complaint, and Urgent Support. Executed systematic dataset scaling (expanding from 30 to 180 examples) which successfully increased average prediction confidence from 70.2% to 85.0% and corrected misclassifications of ambiguous and sarcastic inputs (improving from 61.0% to 80.2%). Conducted rigorous vulnerability stress-testing against out-of-vocabulary and unrepresented administrative inputs to identify, isolate, and comprehensively document edge-case coercion failures.'
new_ptp1_skills = 'Built a text classifier on the Machine Learning for Kids platform by converting text into numerical tokens and mapping them to three labels: Positive Praise, Negative Complaint, and Urgent Support. Scaled the dataset from 30 to 180 examples, which increased the average prediction confidence from 70.2% to 85.0% and helped fix issues with sarcastic inputs (improving from 61.0% to 80.2%). Also tested the model with out-of-vocabulary and unrepresented inputs to identify and document edge-case failures.'
text = text.replace(old_ptp1_skills, new_ptp1_skills)

old_ptp1_prof = 'In enterprise Information Technology Service Management (ITSM) operations, establishing reliable automated triage is critical for managing large, continuous volumes of end-user feedback. Learning how to properly scale dataset volume and representative diversity directly dictates a neural network\'s predictive accuracy and drastically reduces misclassification risks. Understanding these failure modes, specifically how models hallucinate high confidence scores on completely unrecognized edge cases, is an essential competency for ensuring that dynamic AI systems remain functional, robust, and safe in unpredictable real-world production scenarios.'
new_ptp1_prof = 'In IT Service Management (ITSM), reliable automated sorting is crucial for handling large amounts of user feedback. Knowing how to scale a dataset properly directly improves a model\'s accuracy and cuts down on misclassifications. Understanding failure modes, like how a model can wrongly assign a high confidence score to an edge case it has never seen before, is a vital skill for making sure AI systems actually work safely in real-world scenarios.'
text = text.replace(old_ptp1_prof, new_ptp1_prof)

old_ptp1_ref = '&ldquo;This performance task provided invaluable hands-on exposure to both the immense capabilities and the hidden vulnerabilities inherent in neural networks. While I directly observed how purposefully scaling the training dataset significantly improved the model\'s ability to parse complex human nuances like sarcasm, the most striking and concerning finding was observing how the model forcefully mapped completely unrepresented administrative edge cases into existing categories with an abnormally high false-positive confidence of 96.6%. This alarming realization truly emphasized that deploying responsible AI isn\'t just about training a model to recognize known patterns, it\'s about actively and explicitly programming architectural safeguards for when the model inevitably encounters unknown and unpredictable real-world data.&rdquo;'
new_ptp1_ref = '&ldquo;This task gave me great hands-on experience with both the strengths and weaknesses of neural networks. While adding more examples to the dataset clearly helped the model understand tricky things like sarcasm, the biggest surprise was seeing the model confidently force completely unknown edge cases into its existing categories, hitting a 96.6% false-positive rate. This made me realize that deploying AI safely isn\'t just about training it on what to know, it\'s about making sure you actually code in safeguards for when the system eventually runs into something it doesn\'t recognize.&rdquo;'
text = text.replace(old_ptp1_ref, new_ptp1_ref)


# PT-P2 Replacements
old_ptp2_skills = 'Developed a sophisticated sequential neural network natively in Python utilizing the TensorFlow and Keras libraries, meticulously incorporating embedding layers, global average pooling, and dropout regularization for stabilization. Executed a highly systematic One-Factor-At-A-Time hyperparameter tuning pipeline, evaluating convergence behavior and stochastic gradient variance across 11 distinct experimental configurations. Diagnosed model fit by analyzing sparse categorical cross-entropy loss curves and testing various architectural capacity constraints, ultimately discovering that a 128 hidden dimension coupled with a 0.005 learning rate, a batch size of 32, and a 0.1 dropout rate successfully mitigated overfitting and yielded a peak validation accuracy of 88.89% and an F1-score of 0.8898.'
new_ptp2_skills = 'Built a sequential neural network in Python using TensorFlow and Keras, adding embedding layers, global average pooling, and dropout for regularization. Ran a One-Factor-At-A-Time tuning process across 11 experiments to evaluate the model\'s convergence and variance. Checked the model\'s fit by looking at the loss curves and found that using a 128 hidden dimension, a 0.005 learning rate, a batch size of 32, and a 0.1 dropout rate prevented overfitting and resulted in an 88.89% validation accuracy with an F1-score of 0.8898.'
text = text.replace(old_ptp2_skills, new_ptp2_skills)

old_ptp2_prof = 'Transitioning from the constrained environments of automated no-code heuristics to explicit, code-based optimization provides the granular architectural control necessary to dictate a network\'s entire learning trajectory. In professional AI engineering, the ability to manipulate learning rates, dropout constraints, and batch sizes is what separates functional prototypes from production-ready systems. Mastering how to balance core network capacity against convergence stability is paramount for preventing rote memorization (overfitting), reducing stochastic variance, and ensuring high-quality, generalizable predictions for automated enterprise triage architectures.'
new_ptp2_prof = 'Moving from no-code tools to actual code-based optimization gives you the exact control needed to shape how a network learns. In real-world AI development, knowing how to adjust learning rates, dropout layers, and batch sizes is what turns a basic prototype into a usable system. Learning how to balance the network\'s capacity with its stability is key to preventing overfitting and ensuring the model makes accurate predictions in production.'
text = text.replace(old_ptp2_prof, new_ptp2_prof)

old_ptp2_ref = '&ldquo;By far the most intellectually rewarding aspect of this entire exercise was actively tracking and diagnosing the intricate interactions between training loss and validation loss across varying epochs. Witnessing firsthand how a seemingly minor adjustment, like decreasing the learning rate to 0.001, caused immediate and undeniable underfitting, while increasing it slightly to 0.01 triggered pronounced, chaotic validation divergence, truly solidified my practical understanding of how mathematical gradient updates function under the hood. Ultimately, running these 11 isolated experiments proved to me that successful, robust neural networks do not rely on sheer computing power, but rather on achieving a highly delicate equilibrium between architectural capacity, data representation, and strict regularization.&rdquo;'
new_ptp2_ref = '&ldquo;The best part of this exercise was actually watching the training and validation loss change epoch by epoch. Seeing how a small tweak, like dropping the learning rate to 0.001, caused the model to underfit, while raising it to 0.01 made the validation loss spike out of control, really helped me understand how weight updates work in practice. Running these 11 separate experiments showed me that building a good neural network isn\'t just about having more computing power, but about finding the right balance between the model\'s size, the data it learns from, and how well it is regularized.&rdquo;'
text = text.replace(old_ptp2_ref, new_ptp2_ref)

with open(r'C:\Users\antho\.gemini\antigravity\scratch\anthony-academic-portfolio\index.html', 'w', encoding='utf-8') as f:
    f.write(text)
print('Toned down language across all ITC-C508 details.')

